language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx-18mode
gemfile:
  - gemfiles/Gemfile.rails-2.3.x
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-edge